import { useState } from 'react';
import { Link } from 'react-router';
import { motion } from 'motion/react';
import { CreditCard, Banknote, Wallet, Sparkles, Loader2, CheckCircle2, ShoppingBag } from 'lucide-react';
import { useCart } from '../context/CartContext';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { RadioGroup, RadioGroupItem } from '../components/ui/radio-group';
import { CartItemImage } from '../components/CartItemImage';
import { supabase } from '../../lib/supabase';
import { toast } from 'sonner';
